### ISSUE TITLE
Core action items before initial public release

### ISSUE THREAD

**Issue by johnmyleswhite** [johnmyleswhite/FiniteDiff.jl#2]
- [x] Use Documenter to build a proper site with documentation for the full API
- [x] Write up all known issues on GitHub
- [x] Synchronize all of the TODO's in the code with GitHub issues
- [x] Document the mathematics in the code using the in-source documentation strings
- [x] Provide a proper bibliography
- [x] Document known failure cases to see if they can be improved

**Comment by pkofod** [comment]
Seems like the first box can be checked off, right?

**Comment by johnmyleswhite** [comment]
Yes, thanks.
